/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ffe8319f-da4d-49e9-8c61-b9cc21e89c3a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dk2w9D7yR",
    "aws_user_pools_web_client_id": "2l650l4ejontg2l4c89j8uilsu",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xyeyjubzpjgnbaz6hm7tej4mrm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
