backend:
  name: git-gateway
  branch: master
media_folder: public/img/uploads
public_folder: img/uploads
collections:
  - name: testimonials_collection
    label: Testimonials
    files:
      - label: "Testimonials File"
        name: "testimonials_file"
        file: "content/testimonials.json"
        fields:
          - label: "Testimonials List"
            name: "testimonials"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Title, name: title, widget: string }
              - { label: Message, name: message, widget: string }
              - { label: Note, name: note, widget: string }
              - label: Headshot
                name: headshot
                widget: image
                allow_multiple: false
  - name: faqs_collection
    label: FAQs
    files:
      - label: "FAQs File"
        name: "faqs_file"
        file: "content/faq.json"
        fields:
          - label: "FAQs List"
            name: "faq"
            widget: "list"
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: string }